### ISSUE TITLE
Components in .NET 8 Blazor SSR not working after navigation 

### ISSUE THREAD

**Issue by mdmontesinos** [themesberg/tailwind-blazor-starter#8]
Current project setup does not properly work with .NET 8 Blazor SSR enhanced navigation.

Components that require js such as Carousel only work on first load. After enhanced navigating to another page and returning back to the previous one, the carousel disappears and requires a full reload to show again.

I have also tested the popover and same behaviour happens. The popover only shows on first load or after a full reload.

**Comment by vukasinpetrovic** [comment]
@mdmontesinos Did you maybe find a solution for this? I also just stumbled upon this problem as I setup the same project type, and I'm scratching my head on how to solve it.

**Comment by mdmontesinos** [comment]
If you're using Blazor with Static SSR (Interactive None) and Enhanced Navigation (which is active by default), you must use the "enhancedload" event provided and re-initialize flowbite every time an enhanced navigation occurs.

You should have something like this in App.razor, in the body:
```html
<script src="_framework/blazor.web.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
<script>
    Blazor.addEventListener('enhancedload', () => {
        // https://flowbite.com/docs/getting-started/javascript/
        initFlowbite();
    });
</script>
```

You could also initialize only the specific components of Flowbite you're going to use (to reduce overhead) as is stated in the docs.

Nonetheless, the blazor template in this repo is outdated and also is the documentation on how to install it.

**Comment by vukasinpetrovic** [comment]
@mdmontesinos Thank you a lot!
